/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ClientareaRouteImport } from './routes/_clientarea'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as FormularioRouteImport } from './routes/formulario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedPainelProfissionalRouteImport } from './routes/_authenticated/painel-profissional'
import { Route as ClientareaClienteRouteImport } from './routes/_clientarea.cliente'
import { Route as ClienteAtivarRouteImport } from './routes/cliente.ativar'
import { Route as ClienteDefinirSenhaRouteImport } from './routes/cliente.definir-senha'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as AuthenticatedPainelProfissionalIndexRouteImport } from './routes/_authenticated/painel-profissional.index'
import { Route as AuthenticatedPainelProfissionalAcessosRouteImport } from './routes/_authenticated/painel-profissional.acessos'
import { Route as AuthenticatedPainelProfissionalAgendaRouteImport } from './routes/_authenticated/painel-profissional.agenda'
import { Route as AuthenticatedPainelProfissionalCatalogoRouteImport } from './routes/_authenticated/painel-profissional.catalogo'
import { Route as AuthenticatedPainelProfissionalClientesRouteImport } from './routes/_authenticated/painel-profissional.clientes'
import { Route as AuthenticatedPainelProfissionalEntregasRouteImport } from './routes/_authenticated/painel-profissional.entregas'
import { Route as AuthenticatedPainelProfissionalEquipeRouteImport } from './routes/_authenticated/painel-profissional.equipe'
import { Route as AuthenticatedPainelProfissionalMentoriaRouteImport } from './routes/_authenticated/painel-profissional.mentoria'
import { Route as AuthenticatedPainelProfissionalPedidosRouteImport } from './routes/_authenticated/painel-profissional.pedidos'
import { Route as AuthenticatedPainelProfissionalPsicanaliseRouteImport } from './routes/_authenticated/painel-profissional.psicanalise'
import { Route as AuthenticatedPainelProfissionalS8RouteImport } from './routes/_authenticated/painel-profissional.s8'
import { Route as ClientareaClienteIndexRouteImport } from './routes/_clientarea.cliente.index'
import { Route as ClientareaClienteAgendaRouteImport } from './routes/_clientarea.cliente.agenda'
import { Route as ClientareaClienteContratarRouteImport } from './routes/_clientarea.cliente.contratar'
import { Route as ClientareaClienteEntregasRouteImport } from './routes/_clientarea.cliente.entregas'
import { Route as ClientareaClienteMentoriaRouteImport } from './routes/_clientarea.cliente.mentoria'
import { Route as ClientareaClientePedidosRouteImport } from './routes/_clientarea.cliente.pedidos'
import { Route as ClientareaClientePerfilRouteImport } from './routes/_clientarea.cliente.perfil'
import { Route as ClientareaClienteSessoesRouteImport } from './routes/_clientarea.cliente.sessoes'
import { Route as ApiIntegrationsSiteOrdersRouteImport } from './routes/api/integrations/site-orders'
import { Route as ClientareaClientePedidoOrderIdRouteImport } from './routes/_clientarea.cliente.pedido.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientareaRoute = ClientareaRouteImport.update({
  id: '/_clientarea',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioRoute = FormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelProfissionalRoute =
  AuthenticatedPainelProfissionalRouteImport.update({
    id: '/painel-profissional',
    path: '/painel-profissional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClientareaClienteRoute = ClientareaClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => ClientareaRoute,
} as any)
const ClienteAtivarRoute = ClienteAtivarRouteImport.update({
  id: '/cliente/ativar',
  path: '/cliente/ativar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDefinirSenhaRoute = ClienteDefinirSenhaRouteImport.update({
  id: '/cliente/definir-senha',
  path: '/cliente/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/cliente/login',
  path: '/cliente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelProfissionalIndexRoute =
  AuthenticatedPainelProfissionalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalAcessosRoute =
  AuthenticatedPainelProfissionalAcessosRouteImport.update({
    id: '/acessos',
    path: '/acessos',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalAgendaRoute =
  AuthenticatedPainelProfissionalAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalCatalogoRoute =
  AuthenticatedPainelProfissionalCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalClientesRoute =
  AuthenticatedPainelProfissionalClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalEntregasRoute =
  AuthenticatedPainelProfissionalEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalEquipeRoute =
  AuthenticatedPainelProfissionalEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalMentoriaRoute =
  AuthenticatedPainelProfissionalMentoriaRouteImport.update({
    id: '/mentoria',
    path: '/mentoria',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalPedidosRoute =
  AuthenticatedPainelProfissionalPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalPsicanaliseRoute =
  AuthenticatedPainelProfissionalPsicanaliseRouteImport.update({
    id: '/psicanalise',
    path: '/psicanalise',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const AuthenticatedPainelProfissionalS8Route =
  AuthenticatedPainelProfissionalS8RouteImport.update({
    id: '/s8',
    path: '/s8',
    getParentRoute: () => AuthenticatedPainelProfissionalRoute,
  } as any)
const ClientareaClienteIndexRoute = ClientareaClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientareaClienteRoute,
} as any)
const ClientareaClienteAgendaRoute = ClientareaClienteAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ClientareaClienteRoute,
} as any)
const ClientareaClienteContratarRoute =
  ClientareaClienteContratarRouteImport.update({
    id: '/contratar',
    path: '/contratar',
    getParentRoute: () => ClientareaClienteRoute,
  } as any)
const ClientareaClienteEntregasRoute =
  ClientareaClienteEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => ClientareaClienteRoute,
  } as any)
const ClientareaClienteMentoriaRoute =
  ClientareaClienteMentoriaRouteImport.update({
    id: '/mentoria',
    path: '/mentoria',
    getParentRoute: () => ClientareaClienteRoute,
  } as any)
const ClientareaClientePedidosRoute =
  ClientareaClientePedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => ClientareaClienteRoute,
  } as any)
const ClientareaClientePerfilRoute = ClientareaClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClientareaClienteRoute,
} as any)
const ClientareaClienteSessoesRoute =
  ClientareaClienteSessoesRouteImport.update({
    id: '/sessoes',
    path: '/sessoes',
    getParentRoute: () => ClientareaClienteRoute,
  } as any)
const ApiIntegrationsSiteOrdersRoute =
  ApiIntegrationsSiteOrdersRouteImport.update({
    id: '/api/integrations/site-orders',
    path: '/api/integrations/site-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientareaClientePedidoOrderIdRoute =
  ClientareaClientePedidoOrderIdRouteImport.update({
    id: '/pedido/$orderId',
    path: '/pedido/$orderId',
    getParentRoute: () => ClientareaClienteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/formulario': typeof FormularioRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/painel-profissional': typeof AuthenticatedPainelProfissionalRouteWithChildren
  '/cliente': typeof ClientareaClienteRouteWithChildren
  '/cliente/ativar': typeof ClienteAtivarRoute
  '/cliente/definir-senha': typeof ClienteDefinirSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/painel-profissional/acessos': typeof AuthenticatedPainelProfissionalAcessosRoute
  '/painel-profissional/agenda': typeof AuthenticatedPainelProfissionalAgendaRoute
  '/painel-profissional/catalogo': typeof AuthenticatedPainelProfissionalCatalogoRoute
  '/painel-profissional/clientes': typeof AuthenticatedPainelProfissionalClientesRoute
  '/painel-profissional/entregas': typeof AuthenticatedPainelProfissionalEntregasRoute
  '/painel-profissional/equipe': typeof AuthenticatedPainelProfissionalEquipeRoute
  '/painel-profissional/mentoria': typeof AuthenticatedPainelProfissionalMentoriaRoute
  '/painel-profissional/pedidos': typeof AuthenticatedPainelProfissionalPedidosRoute
  '/painel-profissional/psicanalise': typeof AuthenticatedPainelProfissionalPsicanaliseRoute
  '/painel-profissional/s8': typeof AuthenticatedPainelProfissionalS8Route
  '/cliente/agenda': typeof ClientareaClienteAgendaRoute
  '/cliente/contratar': typeof ClientareaClienteContratarRoute
  '/cliente/entregas': typeof ClientareaClienteEntregasRoute
  '/cliente/mentoria': typeof ClientareaClienteMentoriaRoute
  '/cliente/pedidos': typeof ClientareaClientePedidosRoute
  '/cliente/perfil': typeof ClientareaClientePerfilRoute
  '/cliente/sessoes': typeof ClientareaClienteSessoesRoute
  '/api/integrations/site-orders': typeof ApiIntegrationsSiteOrdersRoute
  '/painel-profissional/': typeof AuthenticatedPainelProfissionalIndexRoute
  '/cliente/': typeof ClientareaClienteIndexRoute
  '/cliente/pedido/$orderId': typeof ClientareaClientePedidoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/formulario': typeof FormularioRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cliente/ativar': typeof ClienteAtivarRoute
  '/cliente/definir-senha': typeof ClienteDefinirSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/painel-profissional/acessos': typeof AuthenticatedPainelProfissionalAcessosRoute
  '/painel-profissional/agenda': typeof AuthenticatedPainelProfissionalAgendaRoute
  '/painel-profissional/catalogo': typeof AuthenticatedPainelProfissionalCatalogoRoute
  '/painel-profissional/clientes': typeof AuthenticatedPainelProfissionalClientesRoute
  '/painel-profissional/entregas': typeof AuthenticatedPainelProfissionalEntregasRoute
  '/painel-profissional/equipe': typeof AuthenticatedPainelProfissionalEquipeRoute
  '/painel-profissional/mentoria': typeof AuthenticatedPainelProfissionalMentoriaRoute
  '/painel-profissional/pedidos': typeof AuthenticatedPainelProfissionalPedidosRoute
  '/painel-profissional/psicanalise': typeof AuthenticatedPainelProfissionalPsicanaliseRoute
  '/painel-profissional/s8': typeof AuthenticatedPainelProfissionalS8Route
  '/cliente/agenda': typeof ClientareaClienteAgendaRoute
  '/cliente/contratar': typeof ClientareaClienteContratarRoute
  '/cliente/entregas': typeof ClientareaClienteEntregasRoute
  '/cliente/mentoria': typeof ClientareaClienteMentoriaRoute
  '/cliente/pedidos': typeof ClientareaClientePedidosRoute
  '/cliente/perfil': typeof ClientareaClientePerfilRoute
  '/cliente/sessoes': typeof ClientareaClienteSessoesRoute
  '/api/integrations/site-orders': typeof ApiIntegrationsSiteOrdersRoute
  '/painel-profissional': typeof AuthenticatedPainelProfissionalIndexRoute
  '/cliente': typeof ClientareaClienteIndexRoute
  '/cliente/pedido/$orderId': typeof ClientareaClientePedidoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_clientarea': typeof ClientareaRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/formulario': typeof FormularioRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/painel-profissional': typeof AuthenticatedPainelProfissionalRouteWithChildren
  '/_clientarea/cliente': typeof ClientareaClienteRouteWithChildren
  '/cliente/ativar': typeof ClienteAtivarRoute
  '/cliente/definir-senha': typeof ClienteDefinirSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/_authenticated/painel-profissional/acessos': typeof AuthenticatedPainelProfissionalAcessosRoute
  '/_authenticated/painel-profissional/agenda': typeof AuthenticatedPainelProfissionalAgendaRoute
  '/_authenticated/painel-profissional/catalogo': typeof AuthenticatedPainelProfissionalCatalogoRoute
  '/_authenticated/painel-profissional/clientes': typeof AuthenticatedPainelProfissionalClientesRoute
  '/_authenticated/painel-profissional/entregas': typeof AuthenticatedPainelProfissionalEntregasRoute
  '/_authenticated/painel-profissional/equipe': typeof AuthenticatedPainelProfissionalEquipeRoute
  '/_authenticated/painel-profissional/mentoria': typeof AuthenticatedPainelProfissionalMentoriaRoute
  '/_authenticated/painel-profissional/pedidos': typeof AuthenticatedPainelProfissionalPedidosRoute
  '/_authenticated/painel-profissional/psicanalise': typeof AuthenticatedPainelProfissionalPsicanaliseRoute
  '/_authenticated/painel-profissional/s8': typeof AuthenticatedPainelProfissionalS8Route
  '/_clientarea/cliente/agenda': typeof ClientareaClienteAgendaRoute
  '/_clientarea/cliente/contratar': typeof ClientareaClienteContratarRoute
  '/_clientarea/cliente/entregas': typeof ClientareaClienteEntregasRoute
  '/_clientarea/cliente/mentoria': typeof ClientareaClienteMentoriaRoute
  '/_clientarea/cliente/pedidos': typeof ClientareaClientePedidosRoute
  '/_clientarea/cliente/perfil': typeof ClientareaClientePerfilRoute
  '/_clientarea/cliente/sessoes': typeof ClientareaClienteSessoesRoute
  '/api/integrations/site-orders': typeof ApiIntegrationsSiteOrdersRoute
  '/_authenticated/painel-profissional/': typeof AuthenticatedPainelProfissionalIndexRoute
  '/_clientarea/cliente/': typeof ClientareaClienteIndexRoute
  '/_clientarea/cliente/pedido/$orderId': typeof ClientareaClientePedidoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bootstrap'
    | '/formulario'
    | '/login'
    | '/reset-password'
    | '/painel-profissional'
    | '/cliente'
    | '/cliente/ativar'
    | '/cliente/definir-senha'
    | '/cliente/login'
    | '/painel-profissional/acessos'
    | '/painel-profissional/agenda'
    | '/painel-profissional/catalogo'
    | '/painel-profissional/clientes'
    | '/painel-profissional/entregas'
    | '/painel-profissional/equipe'
    | '/painel-profissional/mentoria'
    | '/painel-profissional/pedidos'
    | '/painel-profissional/psicanalise'
    | '/painel-profissional/s8'
    | '/cliente/agenda'
    | '/cliente/contratar'
    | '/cliente/entregas'
    | '/cliente/mentoria'
    | '/cliente/pedidos'
    | '/cliente/perfil'
    | '/cliente/sessoes'
    | '/api/integrations/site-orders'
    | '/painel-profissional/'
    | '/cliente/'
    | '/cliente/pedido/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/formulario'
    | '/login'
    | '/reset-password'
    | '/cliente/ativar'
    | '/cliente/definir-senha'
    | '/cliente/login'
    | '/painel-profissional/acessos'
    | '/painel-profissional/agenda'
    | '/painel-profissional/catalogo'
    | '/painel-profissional/clientes'
    | '/painel-profissional/entregas'
    | '/painel-profissional/equipe'
    | '/painel-profissional/mentoria'
    | '/painel-profissional/pedidos'
    | '/painel-profissional/psicanalise'
    | '/painel-profissional/s8'
    | '/cliente/agenda'
    | '/cliente/contratar'
    | '/cliente/entregas'
    | '/cliente/mentoria'
    | '/cliente/pedidos'
    | '/cliente/perfil'
    | '/cliente/sessoes'
    | '/api/integrations/site-orders'
    | '/painel-profissional'
    | '/cliente'
    | '/cliente/pedido/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_clientarea'
    | '/bootstrap'
    | '/formulario'
    | '/login'
    | '/reset-password'
    | '/_authenticated/painel-profissional'
    | '/_clientarea/cliente'
    | '/cliente/ativar'
    | '/cliente/definir-senha'
    | '/cliente/login'
    | '/_authenticated/painel-profissional/acessos'
    | '/_authenticated/painel-profissional/agenda'
    | '/_authenticated/painel-profissional/catalogo'
    | '/_authenticated/painel-profissional/clientes'
    | '/_authenticated/painel-profissional/entregas'
    | '/_authenticated/painel-profissional/equipe'
    | '/_authenticated/painel-profissional/mentoria'
    | '/_authenticated/painel-profissional/pedidos'
    | '/_authenticated/painel-profissional/psicanalise'
    | '/_authenticated/painel-profissional/s8'
    | '/_clientarea/cliente/agenda'
    | '/_clientarea/cliente/contratar'
    | '/_clientarea/cliente/entregas'
    | '/_clientarea/cliente/mentoria'
    | '/_clientarea/cliente/pedidos'
    | '/_clientarea/cliente/perfil'
    | '/_clientarea/cliente/sessoes'
    | '/api/integrations/site-orders'
    | '/_authenticated/painel-profissional/'
    | '/_clientarea/cliente/'
    | '/_clientarea/cliente/pedido/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClientareaRoute: typeof ClientareaRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  FormularioRoute: typeof FormularioRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClienteAtivarRoute: typeof ClienteAtivarRoute
  ClienteDefinirSenhaRoute: typeof ClienteDefinirSenhaRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  ApiIntegrationsSiteOrdersRoute: typeof ApiIntegrationsSiteOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_clientarea': {
      id: '/_clientarea'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario': {
      id: '/formulario'
      path: '/formulario'
      fullPath: '/formulario'
      preLoaderRoute: typeof FormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel-profissional': {
      id: '/_authenticated/painel-profissional'
      path: '/painel-profissional'
      fullPath: '/painel-profissional'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_clientarea/cliente': {
      id: '/_clientarea/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClientareaClienteRouteImport
      parentRoute: typeof ClientareaRoute
    }
    '/cliente/ativar': {
      id: '/cliente/ativar'
      path: '/cliente/ativar'
      fullPath: '/cliente/ativar'
      preLoaderRoute: typeof ClienteAtivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/definir-senha': {
      id: '/cliente/definir-senha'
      path: '/cliente/definir-senha'
      fullPath: '/cliente/definir-senha'
      preLoaderRoute: typeof ClienteDefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/cliente/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel-profissional/': {
      id: '/_authenticated/painel-profissional/'
      path: '/'
      fullPath: '/painel-profissional/'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalIndexRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/acessos': {
      id: '/_authenticated/painel-profissional/acessos'
      path: '/acessos'
      fullPath: '/painel-profissional/acessos'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalAcessosRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/agenda': {
      id: '/_authenticated/painel-profissional/agenda'
      path: '/agenda'
      fullPath: '/painel-profissional/agenda'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalAgendaRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/catalogo': {
      id: '/_authenticated/painel-profissional/catalogo'
      path: '/catalogo'
      fullPath: '/painel-profissional/catalogo'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalCatalogoRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/clientes': {
      id: '/_authenticated/painel-profissional/clientes'
      path: '/clientes'
      fullPath: '/painel-profissional/clientes'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalClientesRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/entregas': {
      id: '/_authenticated/painel-profissional/entregas'
      path: '/entregas'
      fullPath: '/painel-profissional/entregas'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalEntregasRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/equipe': {
      id: '/_authenticated/painel-profissional/equipe'
      path: '/equipe'
      fullPath: '/painel-profissional/equipe'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalEquipeRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/mentoria': {
      id: '/_authenticated/painel-profissional/mentoria'
      path: '/mentoria'
      fullPath: '/painel-profissional/mentoria'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalMentoriaRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/pedidos': {
      id: '/_authenticated/painel-profissional/pedidos'
      path: '/pedidos'
      fullPath: '/painel-profissional/pedidos'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalPedidosRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/psicanalise': {
      id: '/_authenticated/painel-profissional/psicanalise'
      path: '/psicanalise'
      fullPath: '/painel-profissional/psicanalise'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalPsicanaliseRouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_authenticated/painel-profissional/s8': {
      id: '/_authenticated/painel-profissional/s8'
      path: '/s8'
      fullPath: '/painel-profissional/s8'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalS8RouteImport
      parentRoute: typeof AuthenticatedPainelProfissionalRoute
    }
    '/_clientarea/cliente/': {
      id: '/_clientarea/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClientareaClienteIndexRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/agenda': {
      id: '/_clientarea/cliente/agenda'
      path: '/agenda'
      fullPath: '/cliente/agenda'
      preLoaderRoute: typeof ClientareaClienteAgendaRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/contratar': {
      id: '/_clientarea/cliente/contratar'
      path: '/contratar'
      fullPath: '/cliente/contratar'
      preLoaderRoute: typeof ClientareaClienteContratarRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/entregas': {
      id: '/_clientarea/cliente/entregas'
      path: '/entregas'
      fullPath: '/cliente/entregas'
      preLoaderRoute: typeof ClientareaClienteEntregasRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/mentoria': {
      id: '/_clientarea/cliente/mentoria'
      path: '/mentoria'
      fullPath: '/cliente/mentoria'
      preLoaderRoute: typeof ClientareaClienteMentoriaRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/pedidos': {
      id: '/_clientarea/cliente/pedidos'
      path: '/pedidos'
      fullPath: '/cliente/pedidos'
      preLoaderRoute: typeof ClientareaClientePedidosRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/perfil': {
      id: '/_clientarea/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientareaClientePerfilRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/_clientarea/cliente/sessoes': {
      id: '/_clientarea/cliente/sessoes'
      path: '/sessoes'
      fullPath: '/cliente/sessoes'
      preLoaderRoute: typeof ClientareaClienteSessoesRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
    '/api/integrations/site-orders': {
      id: '/api/integrations/site-orders'
      path: '/api/integrations/site-orders'
      fullPath: '/api/integrations/site-orders'
      preLoaderRoute: typeof ApiIntegrationsSiteOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_clientarea/cliente/pedido/$orderId': {
      id: '/_clientarea/cliente/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/cliente/pedido/$orderId'
      preLoaderRoute: typeof ClientareaClientePedidoOrderIdRouteImport
      parentRoute: typeof ClientareaClienteRoute
    }
  }
}

interface AuthenticatedPainelProfissionalRouteChildren {
  AuthenticatedPainelProfissionalAcessosRoute: typeof AuthenticatedPainelProfissionalAcessosRoute
  AuthenticatedPainelProfissionalAgendaRoute: typeof AuthenticatedPainelProfissionalAgendaRoute
  AuthenticatedPainelProfissionalCatalogoRoute: typeof AuthenticatedPainelProfissionalCatalogoRoute
  AuthenticatedPainelProfissionalClientesRoute: typeof AuthenticatedPainelProfissionalClientesRoute
  AuthenticatedPainelProfissionalEntregasRoute: typeof AuthenticatedPainelProfissionalEntregasRoute
  AuthenticatedPainelProfissionalEquipeRoute: typeof AuthenticatedPainelProfissionalEquipeRoute
  AuthenticatedPainelProfissionalMentoriaRoute: typeof AuthenticatedPainelProfissionalMentoriaRoute
  AuthenticatedPainelProfissionalPedidosRoute: typeof AuthenticatedPainelProfissionalPedidosRoute
  AuthenticatedPainelProfissionalPsicanaliseRoute: typeof AuthenticatedPainelProfissionalPsicanaliseRoute
  AuthenticatedPainelProfissionalS8Route: typeof AuthenticatedPainelProfissionalS8Route
  AuthenticatedPainelProfissionalIndexRoute: typeof AuthenticatedPainelProfissionalIndexRoute
}

const AuthenticatedPainelProfissionalRouteChildren: AuthenticatedPainelProfissionalRouteChildren =
  {
    AuthenticatedPainelProfissionalAcessosRoute:
      AuthenticatedPainelProfissionalAcessosRoute,
    AuthenticatedPainelProfissionalAgendaRoute:
      AuthenticatedPainelProfissionalAgendaRoute,
    AuthenticatedPainelProfissionalCatalogoRoute:
      AuthenticatedPainelProfissionalCatalogoRoute,
    AuthenticatedPainelProfissionalClientesRoute:
      AuthenticatedPainelProfissionalClientesRoute,
    AuthenticatedPainelProfissionalEntregasRoute:
      AuthenticatedPainelProfissionalEntregasRoute,
    AuthenticatedPainelProfissionalEquipeRoute:
      AuthenticatedPainelProfissionalEquipeRoute,
    AuthenticatedPainelProfissionalMentoriaRoute:
      AuthenticatedPainelProfissionalMentoriaRoute,
    AuthenticatedPainelProfissionalPedidosRoute:
      AuthenticatedPainelProfissionalPedidosRoute,
    AuthenticatedPainelProfissionalPsicanaliseRoute:
      AuthenticatedPainelProfissionalPsicanaliseRoute,
    AuthenticatedPainelProfissionalS8Route:
      AuthenticatedPainelProfissionalS8Route,
    AuthenticatedPainelProfissionalIndexRoute:
      AuthenticatedPainelProfissionalIndexRoute,
  }

const AuthenticatedPainelProfissionalRouteWithChildren =
  AuthenticatedPainelProfissionalRoute._addFileChildren(
    AuthenticatedPainelProfissionalRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelProfissionalRoute: typeof AuthenticatedPainelProfissionalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelProfissionalRoute:
    AuthenticatedPainelProfissionalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClientareaClienteRouteChildren {
  ClientareaClienteAgendaRoute: typeof ClientareaClienteAgendaRoute
  ClientareaClienteContratarRoute: typeof ClientareaClienteContratarRoute
  ClientareaClienteEntregasRoute: typeof ClientareaClienteEntregasRoute
  ClientareaClienteMentoriaRoute: typeof ClientareaClienteMentoriaRoute
  ClientareaClientePedidosRoute: typeof ClientareaClientePedidosRoute
  ClientareaClientePerfilRoute: typeof ClientareaClientePerfilRoute
  ClientareaClienteSessoesRoute: typeof ClientareaClienteSessoesRoute
  ClientareaClienteIndexRoute: typeof ClientareaClienteIndexRoute
  ClientareaClientePedidoOrderIdRoute: typeof ClientareaClientePedidoOrderIdRoute
}

const ClientareaClienteRouteChildren: ClientareaClienteRouteChildren = {
  ClientareaClienteAgendaRoute: ClientareaClienteAgendaRoute,
  ClientareaClienteContratarRoute: ClientareaClienteContratarRoute,
  ClientareaClienteEntregasRoute: ClientareaClienteEntregasRoute,
  ClientareaClienteMentoriaRoute: ClientareaClienteMentoriaRoute,
  ClientareaClientePedidosRoute: ClientareaClientePedidosRoute,
  ClientareaClientePerfilRoute: ClientareaClientePerfilRoute,
  ClientareaClienteSessoesRoute: ClientareaClienteSessoesRoute,
  ClientareaClienteIndexRoute: ClientareaClienteIndexRoute,
  ClientareaClientePedidoOrderIdRoute: ClientareaClientePedidoOrderIdRoute,
}

const ClientareaClienteRouteWithChildren =
  ClientareaClienteRoute._addFileChildren(ClientareaClienteRouteChildren)

interface ClientareaRouteChildren {
  ClientareaClienteRoute: typeof ClientareaClienteRouteWithChildren
}

const ClientareaRouteChildren: ClientareaRouteChildren = {
  ClientareaClienteRoute: ClientareaClienteRouteWithChildren,
}

const ClientareaRouteWithChildren = ClientareaRoute._addFileChildren(
  ClientareaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClientareaRoute: ClientareaRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  FormularioRoute: FormularioRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClienteAtivarRoute: ClienteAtivarRoute,
  ClienteDefinirSenhaRoute: ClienteDefinirSenhaRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  ApiIntegrationsSiteOrdersRoute: ApiIntegrationsSiteOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
