"use client";

import { useEffect, useState } from "react";
import { Lang, supportedLanguages, useSiteLanguage } from "./site-language";

const copy = {
  pt: {
    nav:["Início","Ecossistema","Serviços e soluções","LDR RH & Estratégia","Candidatos","Contato"], menu:"Abrir menu", buy:"Contratar um serviço",
    eyebrow:"ESTRATÉGIA · PESSOAS · EMPREENDEDORISMO", title:"Transformando ideias em legados", lead:"O Grupo LDR Essence reúne soluções para pessoas, empresas e empreendedores que desejam crescer com estratégia, propósito e impacto.", know:"Conhecer o ecossistema", values:"Ver serviços e valores", trust:["Atuação internacional","Pagamento seguro","Atendimento humano"],
    position:"UM GRUPO. DIVERSAS SOLUÇÕES.", positionTitle:"Um ecossistema criado para transformar necessidades em caminhos possíveis.", positionText:"Você pode contratar um profissional, estruturar um negócio, fortalecer sua presença digital ou receber orientação estratégica — tudo dentro do mesmo grupo.", ecosystemLabel:"ECOSSISTEMA LDR ESSENCE", ecosystemTitle:"Escolha a frente certa para o seu momento.",
    ecosystem:[["LDR RH & Estratégia","Recrutamento, seleção, consultoria e desenvolvimento de pessoas para empresas e profissionais.","Conhecer a LDR RH & Estratégia"],["Soluções para empreendedores","Sites, marketing, presença digital, sistemas e apoio prático para transformar ideias em negócios.","Ver serviços e valores"],["Mentoria","Orientação individual para organizar ideias, estruturar projetos e avançar com mais clareza.","Conhecer a mentoria"],["Essence Bem-Estar","Conteúdos e experiências voltados ao equilíbrio entre corpo, mente, propósito e resultados.","Em breve"]],
    lecture:["Palestra gratuita","Empreendedorismo sem fronteiras","Um encontro para quem deseja transformar ideias em projetos, negócios e legados.","Entrar no grupo","Falar no WhatsApp"],
    platform:["Plataforma digital","Plataforma de treinamento para empreendedores","Conteúdos e treinamentos para organizar ideias, desenvolver competências e avançar nos negócios.","Conhecer a plataforma"],
    popularLabel:"CONTRATAÇÃO RÁPIDA", popularTitle:"Serviços mais procurados", popularText:"Valores atualizados e pagamento seguro pela Stripe.", popular:[["Recrutamento operacional","10% de desconto · €405 · R$ 2.160 · antes €450 · R$ 2.400","Encontre profissionais para funções operacionais."],["Landing page profissional","10% de desconto · €441 · R$ 1.341 · antes €490 · R$ 1.490","Uma página estratégica para apresentar e vender."],["Plano de marketing","10% de desconto · €261 · R$ 891 · antes €290 · R$ 990","Posicionamento, conteúdo e plano de ação."],["Mentoria individual","€75 · R$ 250","Uma sessão para organizar prioridades e próximos passos."]], details:"Ver detalhes e contratar", all:"Ver todos os serviços, planos e valores",
    rhLabel:"LDR RH & ESTRATÉGIA", rhTitle:"Sua empresa precisa de pessoas. Nós organizamos o caminho.", rhText:"Recrutamento, seleção, busca ativa, profissionais temporários e consultoria para empresas na Bélgica, em Portugal e no Brasil.", rhItems:["Recrutamento operacional: €405 / R$ 2.160 — 10% de desconto","Recrutamento especializado: €810 / R$ 4.320 — 10% de desconto","Cargos executivos e projetos especiais: proposta personalizada"], rhNote:"Os valores menores já incluem o desconto indicado.", rhCta:"Conhecer os serviços de RH", request:"Contratar recrutamento",
    stepsLabel:"COMO FUNCIONA", stepsTitle:"Da escolha ao próximo passo.", steps:[["Escolha","Encontre a solução adequada para sua necessidade."],["Contrate","Pague pelo checkout ou solicite uma proposta personalizada."],["Receba o contato","Nossa equipe confirma os dados e orienta os próximos passos."]],
    founderLabel:"QUEM LIDERA O GRUPO", founderTitle:"Estratégia com essência humana.", founderText:"Luciano Rodrigues Almeida é psicanalista, mentor, gestor de projetos e CEO do Grupo LDR Essence. Sua trajetória conecta desenvolvimento humano, empreendedorismo e visão prática de negócios.", quote:"O sucesso sustentável nasce quando estratégia, pessoas e propósito avançam juntos.", founderCta:"Conhecer a trajetória de Luciano",
    contactLabel:"FALE COM O GRUPO LDR ESSENCE", contactTitle:"Qual solução pode ajudar você agora?", contactText:"Escolha o canal mais confortável. Nossa equipe direcionará sua mensagem para a área certa.", navigation:"Navegação", social:"Redes sociais", footer:"Estratégia para pessoas, empresas e empreendedores.", rights:"Todos os direitos reservados.",
  },
  fr: {
    nav:["Accueil","Écosystème","Services et solutions","LDR RH & Estratégia","Candidats","Contact"], menu:"Ouvrir le menu", buy:"Choisir un service",
    eyebrow:"STRATÉGIE · PERSONNES · ENTREPRENEURIAT", title:"Transformer les idées en héritages", lead:"Grupo LDR Essence réunit des solutions pour les personnes, les entreprises et les entrepreneurs qui souhaitent grandir avec stratégie, sens et impact.", know:"Découvrir l’écosystème", values:"Voir les services et tarifs", trust:["Présence internationale","Paiement sécurisé","Accompagnement humain"],
    position:"UN GROUPE. PLUSIEURS SOLUTIONS.", positionTitle:"Un écosystème créé pour transformer les besoins en voies concrètes.", positionText:"Recrutez un professionnel, structurez une activité, renforcez votre présence digitale ou bénéficiez d’un accompagnement stratégique au sein du même groupe.", ecosystemLabel:"ÉCOSYSTÈME LDR ESSENCE", ecosystemTitle:"Choisissez la branche adaptée à votre moment.",
    ecosystem:[["LDR RH & Estratégia","Recrutement, sélection, conseil RH et développement des personnes pour entreprises et professionnels.","Découvrir LDR RH & Estratégia"],["Solutions pour entrepreneurs","Sites, marketing, présence digitale, systèmes et soutien pratique pour transformer les idées en entreprises.","Voir services et tarifs"],["Mentorat","Accompagnement individuel pour organiser les idées, structurer les projets et avancer avec clarté.","Découvrir le mentorat"],["Essence Bien-être","Contenus et expériences pour l’équilibre entre corps, esprit, raison d’être et résultats.","Bientôt disponible"]],
    lecture:["Conférence gratuite","Entrepreneuriat sans frontières","Une rencontre pour transformer des idées en projets, entreprises et héritages.","Rejoindre le groupe","Parler sur WhatsApp"],
    platform:["Plateforme numérique","Plateforme de formation pour entrepreneurs","Des contenus et formations pour organiser les idées, développer les compétences et faire avancer son activité.","Découvrir la plateforme"],
    popularLabel:"ACHAT RAPIDE", popularTitle:"Services les plus demandés", popularText:"Tarifs actualisés et paiement sécurisé par Stripe.", popular:[["Recrutement opérationnel","10% de remise · 405 € · 2 160 R$ · avant 450 € · 2 400 R$","Trouvez des professionnels pour les fonctions opérationnelles."],["Landing page professionnelle","10% de remise · 441 € · 1 341 R$ · avant 490 € · 1 490 R$","Une page stratégique pour présenter et vendre."],["Plan marketing","10% de remise · 261 € · 891 R$ · avant 290 € · 990 R$","Positionnement, contenu et plan d’action."],["Mentorat individuel","75 € · 250 R$","Une séance pour organiser priorités et prochaines étapes."]], details:"Voir les détails et commander", all:"Voir tous les services, forfaits et tarifs",
    rhLabel:"LDR RH & ESTRATÉGIA", rhTitle:"Votre entreprise a besoin de personnes. Nous organisons le chemin.", rhText:"Recrutement, sélection, sourcing, professionnels temporaires et conseil en Belgique, au Portugal et au Brésil.", rhItems:["Recrutement opérationnel : 405 € / 2 160 R$ — 10% de remise","Recrutement spécialisé : 810 € / 4 320 R$ — 10% de remise","Cadres et projets spéciaux : proposition personnalisée"], rhNote:"Les montants réduits incluent déjà la remise indiquée.", rhCta:"Découvrir les services RH", request:"Commander un recrutement",
    stepsLabel:"COMMENT ÇA MARCHE", stepsTitle:"Du choix à la prochaine étape.", steps:[["Choisissez","Trouvez la solution adaptée à votre besoin."],["Commandez","Payez via le checkout ou demandez une proposition personnalisée."],["Nous vous contactons","Notre équipe confirme les informations et les prochaines étapes."]],
    founderLabel:"DIRECTION DU GROUPE", founderTitle:"La stratégie avec une essence humaine.", founderText:"Luciano Rodrigues Almeida est psychanalyste, mentor, chef de projet et CEO de Grupo LDR Essence. Son parcours relie développement humain, entrepreneuriat et vision pratique des affaires.", quote:"La réussite durable naît lorsque stratégie, personnes et raison d’être avancent ensemble.", founderCta:"Découvrir le parcours de Luciano",
    contactLabel:"CONTACTEZ GRUPO LDR ESSENCE", contactTitle:"Quelle solution peut vous aider maintenant ?", contactText:"Choisissez le canal le plus pratique. Notre équipe orientera votre message vers le bon service.", navigation:"Navigation", social:"Réseaux sociaux", footer:"Stratégie pour les personnes, les entreprises et les entrepreneurs.", rights:"Tous droits réservés.",
  },
  en: {
    nav:["Home","Ecosystem","Services and solutions","LDR RH & Estratégia","Candidates","Contact"], menu:"Open menu", buy:"Hire a service",
    eyebrow:"STRATEGY · PEOPLE · ENTREPRENEURSHIP", title:"Turning ideas into legacies", lead:"Grupo LDR Essence brings together solutions for people, companies and entrepreneurs who want to grow with strategy, purpose and impact.", know:"Explore the ecosystem", values:"View services and prices", trust:["International reach","Secure payments","Human support"],
    position:"ONE GROUP. MULTIPLE SOLUTIONS.", positionTitle:"An ecosystem created to turn needs into practical paths.", positionText:"Hire a professional, structure a business, strengthen your digital presence or receive strategic guidance — all within the same group.", ecosystemLabel:"LDR ESSENCE ECOSYSTEM", ecosystemTitle:"Choose the right branch for your current needs.",
    ecosystem:[["LDR RH & Estratégia","Recruitment, selection, HR consulting and people development for companies and professionals.","Explore LDR RH & Estratégia"],["Solutions for entrepreneurs","Websites, marketing, digital presence, systems and practical support to turn ideas into businesses.","View services and prices"],["Mentoring","Individual guidance to organize ideas, structure projects and move forward with clarity.","Explore mentoring"],["Essence Wellbeing","Content and experiences focused on balance between body, mind, purpose and results.","Coming soon"]],
    lecture:["Free lecture","Entrepreneurship without borders","A meeting for people who want to turn ideas into projects, businesses and legacies.","Join the group","Chat on WhatsApp"],
    platform:["Digital platform","Training platform for entrepreneurs","Content and training to organize ideas, develop skills and move businesses forward.","Explore the platform"],
    popularLabel:"QUICK HIRE", popularTitle:"Most requested services", popularText:"Updated prices and secure Stripe payment.", popular:[["Operational recruitment","10% off · €405 · R$ 2,160 · before €450 · R$ 2,400","Find professionals for operational roles."],["Professional landing page","10% off · €441 · R$ 1,341 · before €490 · R$ 1,490","A strategic page to present and sell."],["Marketing plan","10% off · €261 · R$ 891 · before €290 · R$ 990","Positioning, content and action plan."],["Individual mentoring","€75 · R$ 250","One session to organize priorities and next steps."]], details:"View details and hire", all:"View all services, plans and prices",
    rhLabel:"LDR RH & ESTRATÉGIA", rhTitle:"Your company needs people. We organize the path.", rhText:"Recruitment, selection, active sourcing, temporary professionals and consulting for companies in Belgium, Portugal and Brazil.", rhItems:["Operational recruitment: €405 / R$ 2,160 — 10% off","Specialized recruitment: €810 / R$ 4,320 — 10% off","Executive roles and special projects: custom proposal"], rhNote:"The lower amounts already include the stated discount.", rhCta:"Explore HR services", request:"Hire recruitment",
    stepsLabel:"HOW IT WORKS", stepsTitle:"From choice to the next step.", steps:[["Choose","Find the right solution for your needs."],["Hire","Pay through checkout or request a custom proposal."],["Hear from us","Our team confirms the details and guides the next steps."]],
    founderLabel:"WHO LEADS THE GROUP", founderTitle:"Strategy with a human essence.", founderText:"Luciano Rodrigues Almeida is a psychoanalyst, mentor, project manager and CEO of Grupo LDR Essence. His journey connects human development, entrepreneurship and practical business vision.", quote:"Sustainable success emerges when strategy, people and purpose move forward together.", founderCta:"Discover Luciano's journey",
    contactLabel:"TALK TO GRUPO LDR ESSENCE", contactTitle:"Which solution can help you now?", contactText:"Choose the most convenient channel. Our team will direct your message to the right area.", navigation:"Navigation", social:"Social media", footer:"Strategy for people, companies and entrepreneurs.", rights:"All rights reserved.",
  },
  es: {
    nav:["Inicio","Ecosistema","Servicios y soluciones","LDR RH & Estratégia","Candidatos","Contacto"], menu:"Abrir menú", buy:"Contratar un servicio",
    eyebrow:"ESTRATEGIA · PERSONAS · EMPRENDIMIENTO", title:"Transformando ideas en legados", lead:"Grupo LDR Essence reúne soluciones para personas, empresas y emprendedores que desean crecer con estrategia, propósito e impacto.", know:"Conocer el ecosistema", values:"Ver servicios y precios", trust:["Actuación internacional","Pago seguro","Atención humana"],
    position:"UN GRUPO. DIVERSAS SOLUCIONES.", positionTitle:"Un ecosistema creado para transformar necesidades en caminos posibles.", positionText:"Contrate a un profesional, estructure un negocio, fortalezca su presencia digital o reciba orientación estratégica dentro del mismo grupo.", ecosystemLabel:"ECOSISTEMA LDR ESSENCE", ecosystemTitle:"Elija el área adecuada para su momento.",
    ecosystem:[["LDR RH & Estratégia","Reclutamiento, selección, consultoría y desarrollo de personas para empresas y profesionales.","Conocer LDR RH & Estratégia"],["Soluciones para emprendedores","Sitios web, marketing, presencia digital, sistemas y apoyo práctico para transformar ideas en negocios.","Ver servicios y precios"],["Mentoría","Orientación individual para organizar ideas, estructurar proyectos y avanzar con claridad.","Conocer la mentoría"],["Essence Bienestar","Contenidos y experiencias para el equilibrio entre cuerpo, mente, propósito y resultados.","Próximamente"]],
    lecture:["Conferencia gratuita","Emprendimiento sin fronteras","Un encuentro para transformar ideas en proyectos, negocios y legados.","Entrar al grupo","Hablar por WhatsApp"],
    platform:["Plataforma digital","Plataforma de formación para emprendedores","Contenidos y formaciones para organizar ideas, desarrollar habilidades y hacer avanzar los negocios.","Conocer la plataforma"],
    popularLabel:"CONTRATACIÓN RÁPIDA", popularTitle:"Servicios más solicitados", popularText:"Precios actualizados y pago seguro mediante Stripe.", popular:[["Reclutamiento operacional","10% de descuento · €405 · R$ 2.160 · antes €450 · R$ 2.400","Encuentre profesionales para funciones operativas."],["Landing page profesional","10% de descuento · €441 · R$ 1.341 · antes €490 · R$ 1.490","Una página estratégica para presentar y vender."],["Plan de marketing","10% de descuento · €261 · R$ 891 · antes €290 · R$ 990","Posicionamiento, contenido y plano de acción."],["Mentoría individual","€75 · R$ 250","Una sesión para organizar prioridades y próximos pasos."]], details:"Ver detalles y contratar", all:"Ver todos los servicios, planes y precios",
    rhLabel:"LDR RH & ESTRATÉGIA", rhTitle:"Su empresa necesita personas. Nosotros organizamos el camino.", rhText:"Reclutamiento, selección, búsqueda activa, profesionales temporales y consultoría en Bélgica, Portugal y Brasil.", rhItems:["Reclutamiento operacional: €405 / R$ 2.160 — 10% de descuento","Reclutamiento especializado: €810 / R$ 4.320 — 10% de descuento","Puestos ejecutivos y proyectos especiales: propuesta personalizada"], rhNote:"Los importes menores ya incluyen el descuento indicado.", rhCta:"Conocer los servicios de RR. HH.", request:"Contratar reclutamiento",
    stepsLabel:"CÓMO FUNCIONA", stepsTitle:"De la elección al próximo paso.", steps:[["Elija","Encuentre la solución adecuada para su necesidad."],["Contrate","Pague por el checkout o solicite una propuesta personalizada."],["Reciba el contacto","Nuestro equipo confirma los datos y orienta los próximos pasos."]],
    founderLabel:"QUIÉN DIRIGE EL GRUPO", founderTitle:"Estrategia con esencia humana.", founderText:"Luciano Rodrigues Almeida es psicoanalista, mentor, gestor de proyectos y CEO de Grupo LDR Essence. Su trayectoria conecta desarrollo humano, emprendimiento y visión práctica de negocios.", quote:"El éxito sostenible nace cuando estrategia, personas y propósito avanzan juntos.", founderCta:"Conocer la trayectoria de Luciano",
    contactLabel:"HABLE CON GRUPO LDR ESSENCE", contactTitle:"¿Qué solución puede ayudarle ahora?", contactText:"Elija el canal más cómodo. Nuestro equipo dirigirá su mensaje al área correcta.", navigation:"Navegación", social:"Redes sociales", footer:"Estrategia para personas, empresas y emprendedores.", rights:"Todos los derechos reservados.",
  },
} as const;

const paths = ["/rh", "/solucoes", "/mentoria", "/bem-estar"];
const platformSite = "https://www.lucianoempreendendor.com/";
const lectureGroup = "https://chat.whatsapp.com/IMk7F1zg2rZJdj9NWC664G?s=cl&p=i&mlu=0";
const lectureWhatsapp = "https://wa.me/32492923605?text=Tenho%20interesse%20na%20palestra%20gratuita%20Empreendedorismo%20sem%20Fronteiras";

export default function HomePage() {
  const [menu, setMenu] = useState(false);
  const { lang, chooseLanguage } = useSiteLanguage();
  const c = copy[lang];
  useEffect(()=>{document.title=lang==="fr"?"Grupo LDR Essence | Écosystème stratégique":lang==="en"?"Grupo LDR Essence | Strategic ecosystem":lang==="es"?"Grupo LDR Essence | Ecosistema estratégico":"Grupo LDR Essence | Ecossistema estratégico"},[lang]);
  const withLang = (path: string) => `${path}?lang=${lang}`;
  return <main className="unifiedHome">
    <header className="unifiedHeader">
      <a className="unifiedLogo" href="#inicio">LDR <b>ESSENCE</b><small>GRUPO</small></a>
      <button className="unifiedMenu" aria-label={c.menu} aria-expanded={menu} onClick={() => setMenu(!menu)}>☰</button>
      <nav className={menu ? "open" : ""}><a href="#inicio">{c.nav[0]}</a><a href="#ecossistema">{c.nav[1]}</a><a href={withLang("/solucoes")}>{c.nav[2]}</a><a href={withLang("/rh")}>{c.nav[3]}</a><a href={withLang("/candidatos")}>{c.nav[4]}</a><a href="#contato">{c.nav[5]}</a></nav>
      <div className="unifiedHeaderTools"><div className="langs">{supportedLanguages.map((item:Lang) => <button className={lang === item ? "active" : ""} onClick={() => chooseLanguage(item)} key={item}>{item.toUpperCase()}</button>)}</div><a className="unifiedBuy" href={withLang("/solucoes") + "#precos"}>{c.buy}</a></div>
    </header>
    <section className="unifiedHero" id="inicio"><div className="unifiedHeroCopy"><span>{c.eyebrow}</span><h1>{c.title}</h1><p>{c.lead}</p><div className="unifiedHeroActions"><a href="#ecossistema">{c.know} →</a><a href={withLang("/solucoes") + "#precos"}>{c.values}</a></div><div className="unifiedTrust">{c.trust.map(item => <span key={item}>✓ {item}</span>)}</div></div><div className="unifiedHeroPhoto"><img src="/essence/luciano-hero.jpg" alt="Luciano Rodrigues Almeida, Grupo LDR Essence"/><div><small>FUNDADOR &amp; CEO</small><strong>Luciano Rodrigues Almeida</strong></div></div></section>
    <section className="unifiedPosition"><span>{c.position}</span><h2>{c.positionTitle}</h2><p>{c.positionText}</p></section>
    <section className="unifiedEcosystem" id="ecossistema"><div className="unifiedTitle"><span>{c.ecosystemLabel}</span><h2>{c.ecosystemTitle}</h2></div><div className="unifiedEcosystemGrid">{c.ecosystem.map((item,index) => <article key={item[0]}><b>{["◆","◈","✦","●"][index]}</b><small>0{index+1}</small><h3>{item[0]}</h3><p>{item[1]}</p><a href={withLang(paths[index])}>{item[2]} →</a></article>)}<article className="lectureEcosystemCard"><b>✧</b><small>05</small><span>{c.lecture[0]}</span><h3>{c.lecture[1]}</h3><p>{c.lecture[2]}</p><div><a className="lectureGroup" href={lectureGroup} target="_blank" rel="noreferrer">{c.lecture[3]} →</a><a className="lectureWhatsappSecondary" href={lectureWhatsapp} target="_blank" rel="noreferrer">{c.lecture[4]} →</a></div></article><article className="platformEcosystemCard"><b>▣</b><small>06</small><span>{c.platform[0]}</span><h3>{c.platform[1]}</h3><p>{c.platform[2]}</p><a className="platformWebsite" href={platformSite} target="_blank" rel="noreferrer">{c.platform[3]} →</a></article></div></section>
    <section className="unifiedPopular"><div className="unifiedTitle light"><span>{c.popularLabel}</span><h2>{c.popularTitle}</h2><p>{c.popularText}</p></div><div>{c.popular.map(item => <article key={item[0]}><h3>{item[0]}</h3><strong>{item[1]}</strong><p>{item[2]}</p><a href={withLang("/solucoes") + "#precos"}>{c.details} →</a></article>)}</div><a className="unifiedAllServices" href={withLang("/solucoes") + "#precos"}>{c.all}</a></section>
    <section className="unifiedRhFeature"><div><span>{c.rhLabel}</span><h2>{c.rhTitle}</h2><p>{c.rhText}</p><ul>{c.rhItems.map(item => <li key={item}>{item}</li>)}</ul><small className="unifiedRhPaymentNote">{c.rhNote}</small><div><a href={withLang("/rh")}>{c.rhCta} →</a><a href={withLang("/rh") + "#recrutamento-checkout"}>{c.request}</a></div></div><img src="/essence/luciano-ceo.jpg" alt="LDR RH & Estratégia"/></section>
    <section className="unifiedSteps"><div className="unifiedTitle"><span>{c.stepsLabel}</span><h2>{c.stepsTitle}</h2></div><div>{c.steps.map((item,index) => <article key={item[0]}><b>{index+1}</b><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section>
    <section className="unifiedFounder"><img src="/essence/luciano-proposito.jpg" alt="Luciano Rodrigues Almeida"/><div><span>{c.founderLabel}</span><h2>{c.founderTitle}</h2><p>{c.founderText}</p><blockquote>“{c.quote}”</blockquote><a href={withLang("/luciano")}>{c.founderCta} →</a></div></section>
    <section className="unifiedContact" id="contato"><span>{c.contactLabel}</span><h2>{c.contactTitle}</h2><p>{c.contactText}</p><div><a href="https://wa.me/32492923605" target="_blank" rel="noreferrer">WhatsApp · +32 492 92 36 05</a><a href="mailto:contacto@ldrrhestrategia.com">contacto@ldrrhestrategia.com</a></div></section>
    <footer className="unifiedFooter"><div><a className="unifiedLogo" href="#inicio">LDR <b>ESSENCE</b><small>GRUPO</small></a><p>{c.footer}</p></div><div><strong>{c.navigation}</strong><a href={withLang("/solucoes")}>{c.nav[2]}</a><a href={withLang("/rh")}>{c.nav[3]}</a><a href={withLang("/candidatos")}>{c.nav[4]}</a></div><div><strong>{c.social}</strong><a href="https://www.instagram.com/grupoldressence?igsh=MTlnbmE0ajUxNmQ2dw%3D%3D&amp;utm_source=qr" target="_blank" rel="noreferrer">Instagram Grupo</a><a href="https://www.instagram.com/luciano.ldr.rh/" target="_blank" rel="noreferrer">Instagram Luciano</a><a href="https://www.linkedin.com/in/luciano-rh-estrategia/" target="_blank" rel="noreferrer">LinkedIn</a></div><p>© {new Date().getFullYear()} Grupo LDR Essence. {c.rights}</p></footer>
    <a className="unifiedWhatsapp" href="https://wa.me/32492923605" target="_blank" rel="noreferrer" aria-label="WhatsApp Grupo LDR Essence">WhatsApp</a>
  </main>;
}
