from pathlib import Path

SELLER=Path('rede-comercial-final/vendedor.html')
ADMIN=Path('rede-comercial-final/admin.html')

# -------- Seller --------
s=SELLER.read_text(encoding='utf-8')
if 'id="candidateFlow"' not in s:
    css='''.candidate-flow{border:1px solid #d9c184;background:linear-gradient(145deg,#fffdf7,#fff)}.candidate-steps{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin:12px 0}.candidate-step{border:1px solid var(--l);border-radius:10px;padding:9px;text-align:center;font-size:11px;background:#fff}.candidate-step.active{background:#fff4cc;border-color:#d4a64f}.candidate-step.done{background:#dcfae6;border-color:#9bd7b5}.chat-box{max-height:300px;overflow:auto;border:1px solid var(--l);border-radius:12px;padding:10px;background:#fbfcfe}.chat-msg{margin:7px 0;padding:9px 11px;border-radius:11px;max-width:86%}.chat-msg.seller{margin-left:auto;background:#e8f1ff}.chat-msg.admin{background:#fff3d5}.candidate-catalog{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.locked-note{border:1px dashed #c9d3de;border-radius:12px;padding:13px;background:#f8fafc;color:var(--m)}.approved-only{display:none}.approved-user .approved-only{display:block}.approved-user .candidate-only{display:none}@media(max-width:760px){.candidate-steps{grid-template-columns:repeat(2,1fr)}.candidate-catalog{grid-template-columns:1fr}}'''
    s=s.replace('</style>',css+'</style>',1)

    # Simplify signup and add candidate fields. Keep password for portal access.
    old='<label><span data-i="name">Nome completo</span><input id="suName" class="field"></label><label>E-mail<input id="suEmail" type="email" class="field"></label><label><span data-i="password">Senha</span><input id="suPass" type="password" minlength="6" class="field"></label><label>WhatsApp<input id="suPhone" class="field"></label><label><span data-i="country">País</span><input id="suCountry" class="field"></label><label><span data-i="currency">Moeda</span><select id="suCurrency" class="field"><option>EUR</option><option>BRL</option></select></label><br><button class="btn gold" onclick="signup()" data-i="create">Criar conta e começar</button>'
    new='''<label><span data-i="name">Nome completo</span><input id="suName" class="field" required></label><label>WhatsApp<input id="suPhone" class="field" required placeholder="+32 ..."></label><label>E-mail<input id="suEmail" type="email" class="field" required></label><label><span data-i="password">Senha para acompanhar candidatura</span><input id="suPass" type="password" minlength="6" class="field" required></label><div class="two"><label><span data-i="country">País</span><input id="suCountry" class="field"></label><label>Idioma<select id="suLanguage" class="field"><option value="pt">Português</option><option value="fr">Français</option><option value="en">English</option><option value="es">Español</option></select></label></div><label>Já trabalhou com vendas?<select id="suSalesExp" class="field"><option value="">Prefiro não informar</option><option value="sim">Sim</option><option value="nao">Não</option></select></label><label>Breve apresentação (opcional)<textarea id="suIntro" class="field" rows="3" maxlength="800"></textarea></label><input id="suCurrency" type="hidden" value="EUR"><br><button class="btn gold" onclick="signup()">Quero me candidatar como vendedor LDR</button>'''
    if old in s: s=s.replace(old,new,1)

    # candidate limited area after seller header card
    anchor='<div class="grid"><div class="card stat"><b id="salesCount">0</b>'
    candidate='''<div id="candidateFlow" class="candidate-only"><div class="card candidate-flow"><div class="eyebrow">PROCESSO DE CANDIDATURA</div><h2 id="candidateStatusTitle">Sua candidatura está em análise</h2><p id="candidateStatusText" class="small">Recebemos seus dados. A próxima etapa é uma conversa com a equipe do Grupo LDR Essence.</p><div id="candidateSteps" class="candidate-steps"></div><div id="interviewBox" class="notice"></div></div><div class="two"><div class="card"><h2>Conheça a Rede Comercial LDR</h2><p class="small">Enquanto sua candidatura é analisada, você pode conhecer o modelo de atuação, as comissões e o catálogo resumido.</p><div id="candidateCatalog" class="candidate-catalog"></div><div class="locked-note" style="margin-top:12px">🔒 Academia Comercial, cadastro de vendas, dados financeiros e certificado ficam disponíveis após sua aprovação.</div></div><div class="card"><h2>Falar com a equipe LDR</h2><p class="small">Use este espaço para dúvidas sobre sua candidatura ou entrevista.</p><div id="candidateChat" class="chat-box"></div><textarea id="candidateMessage" class="field" rows="3" maxlength="3000" placeholder="Escreva sua mensagem"></textarea><br><button class="btn primary" onclick="sendCandidateMessage()">Enviar mensagem</button><div id="candidateMsg"></div></div></div></div>'''
    if anchor in s: s=s.replace(anchor,candidate+anchor,1)

    # mark full seller areas as approved-only by IDs/classes via targeted replacements
    s=s.replace('<div class="grid"><div class="card stat"><b id="salesCount">0</b>','<div class="grid approved-only"><div class="card stat"><b id="salesCount">0</b>',1)
    s=s.replace('<div id="onboardingStart" class="card onboarding-start"></div>','<div id="onboardingStart" class="card onboarding-start approved-only"></div>',1)
    s=s.replace('<div class="card"><div class="eyebrow" data-i="yourDevelopment">','<div class="card approved-only"><div class="eyebrow" data-i="yourDevelopment">',1)
    s=s.replace('<div class="card"><h2 data-i="commissionDashTitle">','<div class="card approved-only"><h2 data-i="commissionDashTitle">',1)
    s=s.replace('<div class="card"><div class="section-title"><div><h2 data-i="catalogInside">','<div class="card approved-only"><div class="section-title"><div><h2 data-i="catalogInside">',1)
    s=s.replace('id="paymentDetailsCard" class="card payment-card"','id="paymentDetailsCard" class="card payment-card approved-only"',1)
    s=s.replace('id="recurringPlans" class="card plan-section"','id="recurringPlans" class="card plan-section approved-only"',1)
    s=s.replace('<div class="two"><div class="card"><h2 data-i="registerSale">','<div class="two approved-only"><div class="card"><h2 data-i="registerSale">',1)
    s=s.replace('<div class="card"><div class="notice"><b data-i="contractTitle">','<div class="card approved-only"><div class="notice"><b data-i="contractTitle">',1)

    # signup RPC args
    old_signup="const{data,error}=await db.rpc('ldr_simple_seller_signup',{p_name:E('suName').value.trim(),p_email:E('suEmail').value.trim(),p_password:E('suPass').value,p_phone:E('suPhone').value.trim(),p_country:E('suCountry').value.trim(),p_currency:E('suCurrency').value});"
    new_signup="const{data,error}=await db.rpc('ldr_simple_seller_signup',{p_name:E('suName').value.trim(),p_email:E('suEmail').value.trim(),p_password:E('suPass').value,p_phone:E('suPhone').value.trim(),p_country:E('suCountry').value.trim(),p_currency:E('suCurrency').value,p_language:E('suLanguage').value,p_sales_experience:E('suSalesExp').value||null,p_introduction:E('suIntro').value.trim()||null});"
    s=s.replace(old_signup,new_signup,1)

    # insert candidate JS before statusLabel
    marker='function statusLabel(s)'
    js=r'''const CANDIDATE_STATUS={pt:{pending_review:'Aguardando análise',interview_to_schedule:'Entrevista a agendar',interview_scheduled:'Entrevista agendada',interview_completed:'Entrevista realizada',approved:'Aprovado',rejected:'Não aprovado',suspended:'Suspenso'},fr:{pending_review:'En attente d’analyse',interview_to_schedule:'Entretien à planifier',interview_scheduled:'Entretien planifié',interview_completed:'Entretien réalisé',approved:'Approuvé',rejected:'Non approuvé',suspended:'Suspendu'},en:{pending_review:'Under review',interview_to_schedule:'Interview to schedule',interview_scheduled:'Interview scheduled',interview_completed:'Interview completed',approved:'Approved',rejected:'Not approved',suspended:'Suspended'},es:{pending_review:'En análisis',interview_to_schedule:'Entrevista por agendar',interview_scheduled:'Entrevista agendada',interview_completed:'Entrevista realizada',approved:'Aprobado',rejected:'No aprobado',suspended:'Suspendido'}};
function candidateStatus(s){return (CANDIDATE_STATUS[lang]||CANDIDATE_STATUS.pt)[s]||s}
function renderCandidateSteps(status){const order=['pending_review','interview_to_schedule','interview_scheduled','approved'];const labels=lang==='fr'?['1. Inscription','2. Analyse','3. Entretien','4. Approbation','5. Formation','6. Ventes']:lang==='en'?['1. Registration','2. Review','3. Interview','4. Approval','5. Training','6. Sales']:lang==='es'?['1. Registro','2. Análisis','3. Entrevista','4. Aprobación','5. Formación','6. Ventas']:['1. Cadastro','2. Análise','3. Entrevista','4. Aprovação','5. Treinamento','6. Vendas'];let idx=status==='pending_review'?1:status==='interview_to_schedule'?2:status==='interview_scheduled'||status==='interview_completed'?2:status==='approved'?5:1;E('candidateSteps').innerHTML=labels.map((x,i)=>`<div class="candidate-step ${i<idx?'done':i===idx?'active':''}">${x}</div>`).join('')}
function renderCandidateCatalog(){E('candidateCatalog').innerHTML=C.slice(0,9).map(x=>`<div class="service"><strong>${esc(serviceName(x))}</strong><span class="small">${rates[x[1]]}% · ${esc(serviceDesc(x))}</span></div>`).join('')}
async function loadCandidatePortal(){const{data,error}=await db.rpc('ldr_simple_candidate_portal',{p_token:token()});if(error){console.error(error);return}const c=data.candidate||{};E('candidateStatusTitle').textContent=candidateStatus(c.application_status);renderCandidateSteps(c.application_status);renderCandidateCatalog();const box=E('interviewBox');if(c.interview_at){const d=new Date(c.interview_at);box.innerHTML=`<b>${candidateStatus(c.application_status)}</b><br>${d.toLocaleString()} ${esc(c.interview_timezone||'')}<br>${esc(c.interview_mode||'')} ${c.interview_link?`<br><a class="btn gold" style="margin-top:8px" href="${esc(c.interview_link)}" target="_blank" rel="noopener">Entrar na reunião</a>`:''}${c.interview_notes?`<br><span class="small">${esc(c.interview_notes)}</span>`:''}` }else box.innerHTML='<b>'+candidateStatus(c.application_status)+'</b><br><span class="small">A equipe LDR atualizará aqui os dados da entrevista.</span>';E('candidateChat').innerHTML=(data.messages||[]).map(m=>`<div class="chat-msg ${m.sender_role}"><b>${m.sender_role==='admin'?'LDR':'Você'}</b><br>${esc(m.body)}<br><span class="small">${new Date(m.created_at).toLocaleString()}</span></div>`).join('')||'<p class="small">Nenhuma mensagem ainda.</p>';E('candidateChat').scrollTop=E('candidateChat').scrollHeight}
async function sendCandidateMessage(){const body=E('candidateMessage').value.trim();if(!body)return;const{error}=await db.rpc('ldr_simple_candidate_send_message',{p_token:token(),p_body:body});if(error)return msg('candidateMsg',error.message,false);E('candidateMessage').value='';await loadCandidatePortal()}
'''
    if marker in s: s=s.replace(marker,js+marker,1)

    # in dashboard, toggle approved/limited and load candidate
    needle="showDash();E('sellerName').textContent=data.seller.full_name;"
    repl="showDash();document.body.classList.toggle('approved-user',!!data.approved);E('sellerName').textContent=data.seller.full_name;if(!data.approved)await loadCandidatePortal();"
    s=s.replace(needle,repl,1)
    s=s.replace('window.signup=signup;window.login=login;window.logout=logout;','window.signup=signup;window.login=login;window.logout=logout;window.sendCandidateMessage=sendCandidateMessage;',1)
    SELLER.write_text(s,encoding='utf-8')

# -------- Admin --------
s=ADMIN.read_text(encoding='utf-8')
if 'id="candidateAdminSection"' not in s:
    css='''.candidate-admin-row{border:1px solid var(--line);border-radius:12px;padding:12px;margin:9px 0}.candidate-admin-row.unread{border-color:var(--gold);background:#fffaf0}.candidate-detail{border:1px solid var(--line);border-radius:12px;padding:14px;background:#fbfcfe;margin-top:12px}.admin-chat{max-height:300px;overflow:auto;border:1px solid var(--line);border-radius:10px;padding:10px;background:#fff}.admin-chat-msg{padding:8px 10px;border-radius:10px;margin:6px 0;max-width:85%}.admin-chat-msg.seller{background:#e8f1ff}.admin-chat-msg.admin{margin-left:auto;background:#fff3d5}.candidate-form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}@media(max-width:700px){.candidate-form-grid{grid-template-columns:1fr}}'''
    s=s.replace('</style>',css+'</style>',1)
    section='''<div id="candidateAdminSection" class="card"><h2>Candidatos a vendedores</h2><p class="small">Analise os novos cadastros, converse, agende a entrevista e aprove o acesso completo.</p><div id="candidateAdminRows"></div><div id="candidateAdminDetail" class="candidate-detail hidden"></div></div>'''
    anchor='<div class="card"><h2>Vendedores e valores a pagar</h2>'
    if anchor in s: s=s.replace(anchor,section+anchor,1)

    marker='async function loadPaymentAdmin()'
    js=r'''let selectedCandidate=null;let candidateCache=[];function appLabel(s){return({pending_review:'AGUARDANDO ANÁLISE',interview_to_schedule:'ENTREVISTA A AGENDAR',interview_scheduled:'ENTREVISTA AGENDADA',interview_completed:'ENTREVISTA REALIZADA',approved:'APROVADO',rejected:'NÃO APROVADO',suspended:'SUSPENSO'})[s]||s}
async function loadCandidates(){const{data,error}=await db.rpc('ldr_simple_admin_candidates',{p_token:token()});if(error){console.error(error);return}candidateCache=data||[];E('candidateAdminRows').innerHTML=candidateCache.map(c=>`<div class="candidate-admin-row ${Number(c.unread_messages)>0?'unread':''}"><div class="row"><div style="flex:1"><b>${esc(c.full_name)}</b><br><span class="small">${esc(c.email)} · ${esc(c.phone||'')} · ${esc(c.country||'')} · ${appLabel(c.application_status)}</span>${Number(c.unread_messages)>0?`<br><span class="badge pending">${c.unread_messages} mensagem(ns) nova(s)</span>`:''}</div><button class="btn primary" onclick="openCandidate('${c.id}')">Ver candidato</button></div></div>`).join('')||'<p class="small">Nenhum candidato cadastrado.</p>'}
async function openCandidate(id){selectedCandidate=id;const c=candidateCache.find(x=>x.id===id);if(!c)return;const{data:msgs,error}=await db.rpc('ldr_simple_admin_candidate_thread',{p_token:token(),p_seller_id:id});if(error)return msg(error.message,false);const dt=c.interview_at?new Date(c.interview_at).toISOString().slice(0,16):'';E('candidateAdminDetail').classList.remove('hidden');E('candidateAdminDetail').innerHTML=`<div class="row"><div style="flex:1"><h3>${esc(c.full_name)}</h3><span class="small">${esc(c.email)} · ${esc(c.phone||'')} · ${esc(c.country||'')} · Idioma: ${esc(c.preferred_language||'pt')}</span><p class="small"><b>Experiência em vendas:</b> ${esc(c.sales_experience||'—')}<br><b>Apresentação:</b> ${esc(c.introduction||'—')}</p></div><span class="badge">${appLabel(c.application_status)}</span></div><div class="candidate-form-grid"><label>Status<select id="candStatus" class="field"><option value="pending_review">Aguardando análise</option><option value="interview_to_schedule">Entrevista a agendar</option><option value="interview_scheduled">Entrevista agendada</option><option value="interview_completed">Entrevista realizada</option><option value="approved">Aprovado</option><option value="rejected">Não aprovado</option><option value="suspended">Suspenso</option></select></label><label>Data e horário<input id="candAt" class="field" type="datetime-local" value="${dt}"></label><label>Fuso horário<input id="candTz" class="field" value="${esc(c.interview_timezone||'Europe/Brussels')}"></label><label>Modalidade<input id="candMode" class="field" value="${esc(c.interview_mode||'Google Meet')}"></label><label style="grid-column:1/-1">Link da reunião<input id="candLink" class="field" value="${esc(c.interview_link||'')}"></label><label style="grid-column:1/-1">Observação<textarea id="candNotes" class="field" rows="2">${esc(c.interview_notes||'')}</textarea></label></div><div class="row" style="margin:10px 0"><button class="btn gold" onclick="saveCandidate()">Salvar etapa/entrevista</button><button class="btn primary" onclick="quickApprove()">Aprovar vendedor</button><button class="btn danger" onclick="quickReject()">Não aprovar</button></div><h3>Conversa com candidato</h3><div class="admin-chat">${(msgs||[]).map(m=>`<div class="admin-chat-msg ${m.sender_role}"><b>${m.sender_role==='admin'?'LDR':'Candidato'}</b><br>${esc(m.body)}<br><span class="small">${new Date(m.created_at).toLocaleString('pt-BR')}</span></div>`).join('')||'<p class="small">Nenhuma mensagem.</p>'}</div><textarea id="adminCandidateMessage" class="field" rows="3" maxlength="3000" placeholder="Responder candidato"></textarea><br><button class="btn primary" onclick="sendAdminCandidateMessage()">Enviar mensagem</button>`;E('candStatus').value=c.application_status}
async function saveCandidate(forceStatus){if(!selectedCandidate)return;const status=forceStatus||E('candStatus').value;const at=E('candAt').value?new Date(E('candAt').value).toISOString():null;const{error}=await db.rpc('ldr_simple_admin_candidate_update',{p_token:token(),p_seller_id:selectedCandidate,p_status:status,p_interview_at:at,p_timezone:E('candTz').value||null,p_mode:E('candMode').value||null,p_link:E('candLink').value||null,p_notes:E('candNotes').value||null});if(error)return msg(error.message,false);msg(status==='approved'?'Vendedor aprovado e acesso completo liberado.':'Candidatura atualizada.',true);await loadCandidates();await openCandidate(selectedCandidate)}
async function quickApprove(){await saveCandidate('approved')}async function quickReject(){await saveCandidate('rejected')}
async function sendAdminCandidateMessage(){const body=E('adminCandidateMessage').value.trim();if(!body)return;const{error}=await db.rpc('ldr_simple_admin_candidate_message',{p_token:token(),p_seller_id:selectedCandidate,p_body:body});if(error)return msg(error.message,false);await openCandidate(selectedCandidate);await loadCandidates()}
'''
    if marker in s: s=s.replace(marker,js+marker,1)

    # load candidates with existing wrappers
    s=s.replace('if(token()){await loadTraining();await loadPaymentAdmin()}','if(token()){await loadTraining();await loadPaymentAdmin();await loadCandidates()}',1)
    s=s.replace('window.loginAdmin=loginAdmin;', 'window.loginAdmin=loginAdmin;window.openCandidate=openCandidate;window.saveCandidate=saveCandidate;window.quickApprove=quickApprove;window.quickReject=quickReject;window.sendAdminCandidateMessage=sendAdminCandidateMessage;',1) if 'window.loginAdmin=loginAdmin;' in s else s
    # functions are global declarations, so explicit window assignment is not required.
    ADMIN.write_text(s,encoding='utf-8')

print('candidate flow patch applied')
