from pathlib import Path

seller=Path('rede-comercial-final/vendedor.html')
s=seller.read_text(encoding='utf-8')
if 'id="onlineSaleCard"' not in s:
    css='''.online-sale-card{border:1px solid #d9c184;background:linear-gradient(145deg,#fffdf7,#fff)}.online-sale-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.online-sale-summary{border:1px solid var(--l);border-radius:12px;padding:13px;background:#f8fafc;margin:12px 0}.online-sale-result{border:1px solid #9bd7b5;border-radius:12px;padding:13px;background:#effbf4;margin-top:12px}.online-sale-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.online-sale-actions .btn{flex:1 1 150px}.online-sale-row{border:1px solid var(--l);border-radius:12px;padding:12px;margin:9px 0;background:#fff}.online-pay-badge{display:inline-block;padding:4px 8px;border-radius:999px;font-size:12px;font-weight:800;background:#eef3f7}.online-pay-paid{background:#dcfae6;color:#087443}.online-pay-pending{background:#fff4cc;color:#805900}.online-pay-failed,.online-pay-expired,.online-pay-refunded{background:#fee4e2;color:#b42318}@media(max-width:650px){.online-sale-grid{grid-template-columns:1fr}.online-sale-actions{display:grid;grid-template-columns:1fr}.online-sale-actions .btn{width:100%}}'''
    s=s.replace('</style>',css+'</style>',1)
    anchor='<div class="two approved-only"><div class="card"><h2 data-i="registerSale">Cadastrar uma venda</h2>'
    html='''<div id="onlineSaleCard" class="card online-sale-card approved-only"><div class="eyebrow" id="onlineEyebrow">VENDA ONLINE SEGURA</div><h2 id="onlineTitle">Venda pelo seu painel</h2><p id="onlineIntro" class="small">Escolha um produto oficial, informe o cliente e gere um Checkout Stripe. Preço e comissão são definidos pelo sistema.</p><form id="onlineSaleForm"><label><span id="onlineProductLabel">Produto ou serviço</span><select id="onlineProduct" class="field" required></select></label><div id="onlineProductSummary" class="online-sale-summary"></div><div class="online-sale-grid"><label><span id="onlineClientLabel">Nome do cliente</span><input id="onlineCustomer" class="field" required></label><label><span id="onlineEmailLabel">E-mail do cliente</span><input id="onlineEmail" type="email" class="field" required></label></div><label><span id="onlinePhoneLabel">WhatsApp do cliente (opcional)</span><input id="onlinePhone" class="field" placeholder="+55 / +351 / +32 ..."></label><br><button id="onlineGenerateBtn" class="btn gold" type="submit">GERAR LINK DE PAGAMENTO</button></form><div id="onlineSaleMsg"></div><div id="onlineCheckoutResult"></div><div class="divider"></div><h3 id="onlineMySalesTitle">Minhas vendas online</h3><p id="onlineMySalesHelp" class="small">O pagamento só é confirmado quando o Stripe informa o sistema.</p><div id="onlineSalesList"></div></div>'''
    if anchor not in s: raise SystemExit('seller HTML anchor not found')
    s=s.replace(anchor,html+anchor,1)

    js_anchor="E('saleForm').addEventListener('submit',async e=>{"
    js=r'''const ONLINE_TXT={pt:{eyebrow:'VENDA ONLINE SEGURA',title:'Venda pelo seu painel',intro:'Escolha um produto oficial, informe o cliente e gere um Checkout Stripe. Preço e comissão são definidos pelo sistema.',product:'Produto ou serviço',client:'Nome do cliente',email:'E-mail do cliente',phone:'WhatsApp do cliente (opcional)',generate:'GERAR LINK DE PAGAMENTO',my:'Minhas vendas online',help:'O pagamento só é confirmado quando o Stripe informa o sistema.',copy:'COPIAR LINK',wa:'ENVIAR PELO WHATSAPP',open:'ABRIR PAGAMENTO',created:'Link de pagamento criado com segurança.',pending:'Aguardando pagamento',paid:'Pagamento confirmado',failed:'Pagamento falhou',expired:'Link expirado',refunded:'Reembolsado',renewal:'Renovação de assinatura'},fr:{eyebrow:'VENTE EN LIGNE SÉCURISÉE',title:'Vendez depuis votre espace',intro:'Choisissez une offre officielle, renseignez le client et générez un Checkout Stripe. Le prix et la commission sont définis par le système.',product:'Produit ou service',client:'Nom du client',email:'E-mail du client',phone:'WhatsApp du client (facultatif)',generate:'GÉNÉRER LE LIEN DE PAIEMENT',my:'Mes ventes en ligne',help:'Le paiement est confirmé uniquement après validation par Stripe.',copy:'COPIER LE LIEN',wa:'ENVOYER PAR WHATSAPP',open:'OUVRIR LE PAIEMENT',created:'Lien de paiement sécurisé créé.',pending:'Paiement en attente',paid:'Paiement confirmé',failed:'Paiement échoué',expired:'Lien expiré',refunded:'Remboursé',renewal:'Renouvellement d’abonnement'},en:{eyebrow:'SECURE ONLINE SALE',title:'Sell from your dashboard',intro:'Choose an official product, enter the client details and generate a Stripe Checkout. Price and commission are set by the system.',product:'Product or service',client:'Client name',email:'Client email',phone:'Client WhatsApp (optional)',generate:'GENERATE PAYMENT LINK',my:'My online sales',help:'Payment is confirmed only after Stripe validates it.',copy:'COPY LINK',wa:'SEND VIA WHATSAPP',open:'OPEN PAYMENT',created:'Secure payment link created.',pending:'Awaiting payment',paid:'Payment confirmed',failed:'Payment failed',expired:'Link expired',refunded:'Refunded',renewal:'Subscription renewal'},es:{eyebrow:'VENTA ONLINE SEGURA',title:'Vende desde tu panel',intro:'Elige un producto oficial, informa los datos del cliente y genera un Checkout Stripe. El precio y la comisión los define el sistema.',product:'Producto o servicio',client:'Nombre del cliente',email:'E-mail del cliente',phone:'WhatsApp del cliente (opcional)',generate:'GENERAR LINK DE PAGO',my:'Mis ventas online',help:'El pago solo se confirma cuando Stripe lo valida.',copy:'COPIAR LINK',wa:'ENVIAR POR WHATSAPP',open:'ABRIR PAGO',created:'Link de pago seguro creado.',pending:'Esperando pago',paid:'Pago confirmado',failed:'Pago fallido',expired:'Link expirado',refunded:'Reembolsado',renewal:'Renovación de suscripción'}};
let onlineCatalog=[];let onlineCheckout=null;
function ot(k){return(ONLINE_TXT[lang]||ONLINE_TXT.pt)[k]||k}
function renderOnlineLabels(){if(!E('onlineSaleCard'))return;E('onlineEyebrow').textContent=ot('eyebrow');E('onlineTitle').textContent=ot('title');E('onlineIntro').textContent=ot('intro');E('onlineProductLabel').textContent=ot('product');E('onlineClientLabel').textContent=ot('client');E('onlineEmailLabel').textContent=ot('email');E('onlinePhoneLabel').textContent=ot('phone');E('onlineGenerateBtn').textContent=ot('generate');E('onlineMySalesTitle').textContent=ot('my');E('onlineMySalesHelp').textContent=ot('help')}
function onlineSelected(){return onlineCatalog.find(x=>x.catalog_key===E('onlineProduct')?.value)||onlineCatalog[0]}
function updateOnlineProductSummary(){const x=onlineSelected();if(!x||!E('onlineProductSummary'))return E('onlineProductSummary').innerHTML='<span class="small">—</span>';const cc=Math.round(Number(x.amount_cents)*Number(x.commission_rate)/100);const recurring=x.billing_mode==='subscription'?(lang==='fr'?' · Abonnement':lang==='en'?' · Subscription':lang==='es'?' · Suscripción':' · Assinatura'):'';E('onlineProductSummary').innerHTML=`<b>${esc(x.name)}</b><br><span class="small">${money(x.amount_cents,x.currency)}${recurring} · ${x.commission_rate}% ${lang==='fr'?'commission':lang==='en'?'commission':lang==='es'?'comisión':'comissão'} = <b>${money(cc,x.currency)}</b></span>`}
async function loadOnlineCatalog(){if(!document.body.classList.contains('approved-user')||!token()||!E('onlineProduct'))return;const{data,error}=await db.rpc('ldr_seller_catalog',{p_token:token()});if(error){console.error('catalog online',error);return}onlineCatalog=data||[];const current=E('onlineProduct').value;E('onlineProduct').innerHTML=onlineCatalog.map(x=>`<option value="${esc(x.catalog_key)}">${x.source_site==='lucianoempreendendor'?'Empreendedor':'LDR'} · ${esc(x.name)} · ${money(x.amount_cents,x.currency)}</option>`).join('');if(current&&onlineCatalog.some(x=>x.catalog_key===current))E('onlineProduct').value=current;updateOnlineProductSummary();renderOnlineLabels()}
function onlinePayLabel(s){if(s==='paid')return ot('paid');if(s==='failed')return ot('failed');if(s==='expired')return ot('expired');if(s==='refunded')return ot('refunded');return ot('pending')}
async function refreshOnlineSales(){if(!document.body.classList.contains('approved-user')||!token()||!E('onlineSalesList'))return;const{data,error}=await db.rpc('ldr_simple_seller_dashboard',{p_token:token()});if(error)return;const rows=(data.sales||[]).filter(x=>x.sale_source==='stripe_checkout'||x.sale_source==='stripe_subscription_renewal');E('onlineSalesList').innerHTML=rows.map(x=>{const ps=x.payment_status||'payment_pending';const klass=ps==='paid'?'paid':ps==='refunded'?'refunded':ps==='failed'?'failed':ps==='expired'?'expired':'pending';return `<div class="online-sale-row"><div class="row"><div style="flex:1"><b>${esc(x.service_name)}</b>${x.sale_source==='stripe_subscription_renewal'?` <span class="badge">${ot('renewal')}</span>`:''}<br><span class="small">${esc(x.customer_name)}${x.customer_email?' · '+esc(x.customer_email):''}<br>${money(x.amount_cents,x.currency)} · ${x.commission_rate}% = ${money(x.commission_original_cents??x.commission_cents,x.currency)}</span><br><span class="online-pay-badge online-pay-${klass}">${onlinePayLabel(ps)}</span></div>${x.checkout_url&&ps!=='paid'&&ps!=='refunded'?`<button class="btn ghost" type="button" onclick="copySaleCheckout('${esc(x.id)}')">${ot('copy')}</button>`:''}</div></div>`}).join('')||'<p class="small">—</p>';window._onlineSales=rows}
async function createOnlineSale(e){e.preventDefault();const x=onlineSelected();if(!x)return;const btn=E('onlineGenerateBtn');btn.disabled=true;const old=btn.textContent;btn.textContent='...';E('onlineSaleMsg').innerHTML='';try{const r=await fetch('https://www.lucianoempreendendor.com/.netlify/functions/create-seller-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token(),catalog_key:x.catalog_key,customer_name:E('onlineCustomer').value.trim(),customer_email:E('onlineEmail').value.trim(),customer_phone:E('onlinePhone').value.trim(),quantity:1})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Checkout error');onlineCheckout=d;E('onlineCheckoutResult').innerHTML=`<div class="online-sale-result"><b>${ot('created')}</b><br><span class="small">${esc(d.name)} · ${money(d.amount_cents,d.currency)} · ${d.commission_rate}% = ${money(d.commission_cents,d.currency)}</span><div class="online-sale-actions"><button class="btn ghost" type="button" onclick="copyOnlineCheckout()">${ot('copy')}</button><button class="btn primary" type="button" onclick="sendOnlineWhatsApp()">${ot('wa')}</button><a class="btn gold" href="${esc(d.url)}" target="_blank" rel="noopener">${ot('open')}</a></div></div>`;await refreshOnlineSales()}catch(err){msg('onlineSaleMsg',err.message,false)}finally{btn.disabled=false;btn.textContent=old}}
async function copyOnlineCheckout(){if(!onlineCheckout?.url)return;await navigator.clipboard.writeText(onlineCheckout.url);msg('onlineSaleMsg',lang==='fr'?'Lien copié.':lang==='en'?'Link copied.':lang==='es'?'Link copiado.':'Link copiado.',true)}
async function copySaleCheckout(id){const x=(window._onlineSales||[]).find(v=>v.id===id);if(!x?.checkout_url)return;await navigator.clipboard.writeText(x.checkout_url)}
function sendOnlineWhatsApp(){if(!onlineCheckout?.url)return;const x=onlineSelected();const name=E('onlineCustomer').value.trim();const txt=lang==='fr'?`Bonjour ${name}, voici le lien sécurisé pour le paiement de ${x.name}. Montant: ${money(onlineCheckout.amount_cents,onlineCheckout.currency)}. Paiement traité par le Groupe LDR Essence via Stripe. ${onlineCheckout.url}`:lang==='en'?`Hello ${name}, here is the secure payment link for ${x.name}. Amount: ${money(onlineCheckout.amount_cents,onlineCheckout.currency)}. Payment is processed by LDR Essence Group via Stripe. ${onlineCheckout.url}`:lang==='es'?`Hola ${name}, aquí tienes el enlace seguro para el pago de ${x.name}. Importe: ${money(onlineCheckout.amount_cents,onlineCheckout.currency)}. Pago procesado por Grupo LDR Essence mediante Stripe. ${onlineCheckout.url}`:`Olá ${name}, segue o link seguro para pagamento de ${x.name}. Valor: ${money(onlineCheckout.amount_cents,onlineCheckout.currency)}. Pagamento processado pelo Grupo LDR Essence via Stripe. ${onlineCheckout.url}`;window.open('https://wa.me/?text='+encodeURIComponent(txt),'_blank','noopener')}
E('onlineSaleForm').addEventListener('submit',createOnlineSale);E('onlineProduct').addEventListener('change',updateOnlineProductSummary);
window.copyOnlineCheckout=copyOnlineCheckout;window.copySaleCheckout=copySaleCheckout;window.sendOnlineWhatsApp=sendOnlineWhatsApp;
'''
    if js_anchor not in s: raise SystemExit('seller JS anchor not found')
    s=s.replace(js_anchor,js+js_anchor,1)
    old="await loadPayment();const changed=await retryPendingFx();"
    new="await loadPayment();await loadOnlineCatalog();await refreshOnlineSales();const changed=await retryPendingFx();"
    if old not in s: raise SystemExit('seller load wrapper anchor not found')
    s=s.replace(old,new,1)
    old2="await _payBaseDashboard();await loadPayment()"
    new2="await _payBaseDashboard();await loadPayment();await loadOnlineCatalog();await refreshOnlineSales()"
    s=s.replace(old2,new2,1)
    seller.write_text(s,encoding='utf-8')

admin=Path('rede-comercial-final/admin.html')
a=admin.read_text(encoding='utf-8')
if 'id="stripeOnlineAdmin"' not in a:
    a=a.replace('</style>','.stripe-online-row{border:1px solid var(--line);border-radius:12px;padding:12px;margin:9px 0;background:#fbfcfe}.stripe-alert{background:#fee8e6;color:var(--bad);padding:7px 9px;border-radius:8px;font-size:12px;font-weight:800}.stripe-ok{background:#dcfae6;color:#087443}.stripe-warn{background:#fff4cc;color:#805900}</style>',1)
    anchor='<div class="card"><h2>Vendas para conferir</h2><div id="sales"></div></div>'
    block='<div id="stripeOnlineAdmin" class="card"><h2>Vendas online Stripe</h2><p class="small">Pagamentos gerados pelo painel dos vendedores. O status financeiro vem diretamente do Stripe; não libere comissão de pagamento pendente.</p><div id="stripeOnlineRows"></div></div>'
    if anchor not in a: raise SystemExit('admin HTML anchor not found')
    a=a.replace(anchor,block+anchor,1)
    js_anchor='let selectedCandidate=null;'
    js=r'''function stripePayLabel(s){return({payment_pending:'Aguardando pagamento',paid:'Pagamento confirmado',failed:'Pagamento falhou',expired:'Link expirado',refunded:'Reembolsado',manual:'Manual'})[s]||s}
function renderStripeAdmin(sales){if(!E('stripeOnlineRows'))return;const rows=(sales||[]).filter(x=>x.sale_source==='stripe_checkout'||x.sale_source==='stripe_subscription_renewal');E('stripeOnlineRows').innerHTML=rows.map(x=>{const pc=x.payout_currency||x.currency;const comm=x.commission_converted_cents??x.commission_cents;const cls=x.payment_status==='paid'?'stripe-ok':x.payment_status==='payment_pending'?'stripe-warn':'stripe-alert';return `<div class="stripe-online-row"><div class="row"><div style="flex:1"><b>${esc(x.seller_name)}</b> → ${esc(x.customer_name)}<br><b>${esc(x.service_name)}</b> · ${money(x.amount_cents,x.currency)}<br><span class="small">${esc(x.customer_email||'')} · Comissão ${x.commission_rate}% · ${money(x.commission_original_cents??x.commission_cents,x.currency)}${x.conversion_status==='pending'?' · conversão pendente':` · a pagar ${money(comm,pc)} (${pc})`}</span><br><span class="badge ${cls}">${stripePayLabel(x.payment_status)}</span>${x.sale_source==='stripe_subscription_renewal'?'<span class="badge"> Renovação </span>':''}${x.commission_adjustment_required?'<div class="stripe-alert" style="margin-top:7px">COMISSÃO A AJUSTAR — reembolso após pagamento da comissão</div>':''}<br><span class="small">Checkout: ${esc(x.stripe_checkout_session_id||'—')}<br>Payment Intent: ${esc(x.stripe_payment_intent_id||'—')}</span></div></div></div>`}).join('')||'<p class="small">Nenhuma venda online ainda.</p>'}
'''
    if js_anchor not in a: raise SystemExit('admin JS anchor not found')
    a=a.replace(js_anchor,js+js_anchor,1)
    # Add rendering after main sales list is built, before payouts rendering.
    marker="E('payouts').innerHTML="
    if marker not in a: raise SystemExit('admin payouts anchor not found')
    a=a.replace(marker,"renderStripeAdmin(data.sales||[]);"+marker,1)
    # Do not expose release/refuse controls for Stripe pending payments in the legacy sales list.
    a=a.replace("x.status==='pending'&&x.conversion_status!=='pending'", "x.status==='pending'&&x.sale_source!=='stripe_checkout'&&x.sale_source!=='stripe_subscription_renewal'&&x.conversion_status!=='pending'",1)
    a=a.replace("x.status==='pending'?`<button class=\"btn danger\"", "x.status==='pending'&&x.sale_source!=='stripe_checkout'&&x.sale_source!=='stripe_subscription_renewal'?`<button class=\"btn danger\"",1)
    admin.write_text(a,encoding='utf-8')

print('secure online sales portal patch applied')
